# Generated by Django 4.1.13 on 2024-04-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.TextField()),
                ('password', models.CharField(max_length=200)),
                ('shippingAddress', models.CharField(max_length=200)),
                ('cart', models.JSONField(blank=True, null=True)),
                ('reviews', models.JSONField(blank=True, null=True)),
                ('questions', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
